dist: focal
language: ruby

addons:
  chrome: stable

cache:
  bundler: true

git:
  depth: false

rvm:
  - 3.0.0

services:
  - postgresql

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - yarn install
  - psql -c 'create database valczykanger_test;' -U postgres

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
